# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    - run: npm run build 
    - name: docker_test
      run: docker build -t mbarjot/nginx:latest .
    - name: log_in_to_docker_registry
      uses: docker/login-action@v1
      with: 
        username: ${{secrets.USERNAME}}
        password: ${{secrets.TOKEN}}
    - run: echo "tag=$(git branch --show-current)_$(git log -n1 --format=format:\"%H\")" >> $GITHUB_ENV
    - run: docker build -t mbarjot/xebxke:${{env.tag}} .
    - run: docker push  mbarjot/xebxke:${{env.tag}}
      
